version: "3.8"
services:
  dropbox_consumer:
    build: .
    image: yourdockerhubuser/dropbox-consumer:1.0
    container_name: dropbox_consumer
    user: "${PUID:-1000}:${PGID:-1000}"   # replace with your numeric UID:GID or set env
    volumes:
      - /opt/testin:/source:ro
      - /opt/testout:/consume:rw
    environment:
      - SOURCE=/source
      - DEST=/consume
      - PRESERVE_DIRS=true
      - RECURSIVE=true
      # WARNING: COPY_EMPTY_DIRS copies empty directories which may waste resources 
      # and create unnecessary directory structure in your document management system.
      # Only enable if you specifically need empty folder structure preservation.
      - COPY_EMPTY_DIRS=true
    restart: unless-stopped

