version: "3.8"
services:
  dropbox_consumer:
    image: trusmith/dropbox-consumer:latest
    container_name: dropbox_consumer
    user: "${PUID:-1000}:${PGID:-1000}"   # replace with your numeric UID:GID or set env
    volumes:
      - /opt/testin:/source:ro
      - /opt/testout:/consume:rw
      # Persistent state storage in current directory (auto-created)
      - ./state:/app/state:rw
    environment:
      - SOURCE=/source
      - DEST=/consume
      - PRESERVE_DIRS=true
      - RECURSIVE=true
      # WARNING: COPY_EMPTY_DIRS copies empty directories which may waste resources 
      # and create unnecessary directory structure in your document management system.
      # Only enable if you specifically need empty folder structure preservation.
      - COPY_EMPTY_DIRS=false
      # Persistent state configuration
      - STATE_DIR=/app/state
      - STATE_CLEANUP_DAYS=30
    restart: unless-stopped

