name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: trusmith/dropbox-consumer
  GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Changed from read to write for creating releases
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          ${{ env.GHCR_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Debug metadata output
      run: |
        echo "Generated tags: ${{ steps.meta.outputs.tags }}"
        echo "Generated labels: ${{ steps.meta.outputs.labels }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
        echo "Is default branch: ${{ github.ref == 'refs/heads/main' }}"

    - name: Fallback tag generation
      id: fallback
      if: steps.meta.outputs.tags == ''
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.GHCR_IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
        else
          echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags || steps.fallback.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Debug README content
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        echo "=== README.md content ===" 
        head -20 ./README.md
        echo "=== End README preview ==="
        echo "Docker Hub Repository: ${{ env.IMAGE_NAME }}"
        echo "GitHub Package: ${{ env.GHCR_IMAGE_NAME }}"
        echo "Username: ${{ secrets.DOCKER_USERNAME }}"

    - name: Update Docker Hub description
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      continue-on-error: true  # Don't fail the entire workflow if this step fails
      uses: peter-evans/dockerhub-description@v4  # Updated to v4 for better reliability
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./README.md
        short-description: "File monitoring service for document processing and synchronization"
        enable-url-completion: true

  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if release already exists
        if gh release view "${{ github.ref_name }}" >/dev/null 2>&1; then
          echo "Release ${{ github.ref_name }} already exists, skipping creation"
          exit 0
        fi
        
        # Extract version from tag (e.g., v3.0 -> 3.0)
        VERSION=${GITHUB_REF_NAME#v}
        
        # Check if release notes file exists, otherwise use default content
        if [ -f "RELEASE_NOTES_${GITHUB_REF_NAME}.md" ]; then
          RELEASE_BODY="$(cat RELEASE_NOTES_${GITHUB_REF_NAME}.md)"
        else
          RELEASE_BODY="## Changes
        
        See commit history for detailed changes in this release.
        
        ## Docker Images
        - \`trusmith/dropbox-consumer:${VERSION}\`
        - \`trusmith/dropbox-consumer:latest\`
        - \`ghcr.io/john-lazarus/dropbox-consumer:${VERSION}\`"
        fi
        
        # Create the release
        gh release create "${{ github.ref_name }}" \
          --title "${{ github.ref_name }} - Dropbox Consumer" \
          --notes "$RELEASE_BODY" \
          --latest